### ISSUE TITLE
Empty diagrams

### ISSUE THREAD

**Issue by eric-panier-opalrt** [structurizr/onpremises#75] opened 2023-10-11 14:17 UTC
### Description

Hi,

When we load the workspaces/veniam_workspace.dsl in the attached zip file "empty_diagrams_bug.zip" on Structurizr onpremises version: 3124 and 3194 (Latest). Structurizr seems to work well but when we click on a diagram we get a empty page. Structurizr seems to load the diagram but nothing appears.

If we edit the workspaces/veniam_workspace.dsl file and comment any line 11, 12, 13 or 14. Everything works well.

We tried to identify the views producing the issue but we haven’t been able to find the conditions to produce it. We thought about deployment views or dynamic views but we are able to load correctly all of them separately but not all together.

[empty_diagrams_bug.zip](https://github.com/structurizr/onpremises/files/12870882/empty_diagrams_bug.zip)

Thanks for your help and sorry to not be able to help you more to identify the conditions of this bug.

Strange things is that it works well with Structurizr Lite 3124 and Latest.

This is a blocker for our project,
thanks,
Best regards.

Eric PANIER

OPAL-RT TECHNOLOGIES

### Steps to reproduce

If we edit the workspaces/veniam_workspace.dsl file and comment any line 11, 12, 13 or 14. Everything works well.

### Screenshot

![image](https://github.com/structurizr/onpremises/assets/10672173/224376f2-b3e7-4818-85ed-62f66d32a48b)

### Configuration

structurizr onpremises build 3124 and 3194 (Latest)

### Severity

Major

### Priority

High

### Resolution

I have no budget and there's no rush, please fix this for free

**Comment by eric-panier-opalrt** [comment] 2023-11-01 15:23
Hi Simon,

Did you have time to check this issue please ?

Thanks for your time.
Best regards.
Eric PANIER
OPAL-RT TECHNOLOGIES

**Comment by simonbrowndotje** [comment] 2023-11-01 16:49
> Did you have time to check this issue please ?

I'm busy travelling around running workshops/speaking at conferences/etc during October/November so I have limited time for free support at the moment I'm afraid. I took a quick look at the ZIP file, and you seem to have a lot of views - perhaps your issue is already solved in build 3203+?

**Comment by eric-panier-opalrt** [comment] 2023-11-01 17:37
Thanks @simonbrowndotje,

I understand. I will try the latest build to check and will confirm if it is solved or not...

Have good conferences and workshops :-)
Eric

**Comment by eric-panier-opalrt** [comment] 2023-11-06 15:25
Hi @simonbrowndotje, 
I did a mistake when I created this issue.
I created it with my account eric-panier-opalrt. 
But I should have create it with our company account (the one I'm using to write this comment) to be sure this issue will be considered in our official support. **Because we pay for the support.**
Is it possible to move it or do I need to recreate it ?

Thanks.
Best regards.
Eric PANIER
OPAL-RT TECHNOLOGIES

**Comment by opalrt** [comment] 2023-11-06 15:34
Hi @simonbrowndotje,
I did a mistake when I created this issue.
I created it with my account eric-panier-opalrt.
But I should have create it with our company account (the one I'm using to write this comment) to be sure this issue will be considered in our official support. Because we pay for the support.
Is it possible to move it or do I need to recreate it ?

Thanks.
Best regards.
Eric PANIER
OPAL-RT TECHNOLOGIES

**Comment by simonbrowndotje** [comment] 2023-11-06 15:40
No problem, feel free to e-mail help@structurizr.com with details of your on-premises support contract. 👍

**Comment by simonbrowndotje** [comment] 2023-11-06 16:40
I've just tried your workspace with `structurizr/onpremises:3208` (Docker image), pushed via v1.34.0 of the Structurizr CLI and all diagrams seem to render for me. Did you try upgrading everything?

**Comment by opalrt** [comment] 2023-11-06 17:56
Thanks for the info. I did not test latest version yet, I am waiting my IT service. I will let you know when it is done...

**Comment by simonbrowndotje** [comment] 2023-11-08 08:59
Is this the prebuilt Docker image or are you using the .war file? And have you tried using private browsing/another web browser/clearing your browser cache? Any errors in the JavaScript console or the server logs?

I would be tempted to install a basic on-premises installation on your local computer to ascertain whether this is a problem with something in your environment.

**Comment by opalrt** [comment] 2023-11-08 15:46
Thanks for clues !
I see this error in javascript console, it seems it is a problem with the payload size : (Payload Too Large)
[structurizr.opal-rt.com-1699458123656.log](https://github.com/structurizr/onpremises/files/13298650/structurizr.opal-rt.com-1699458123656.log)

First time I load there are a lot of error about thumbnails error 404 but I guess it is normal because I did not clicked on them to build them.

**Comment by simonbrowndotje** [comment] 2023-11-08 15:51
I'm assuming that you're not using the prebuilt Docker image then? If so, it's a relatively straightforward fix; see `maxPostSize` at https://tomcat.apache.org/tomcat-9.0-doc/config/http.html

**Comment by opalrt** [comment] 2023-11-08 16:04
Thanks, I'am contacting my IT-support to check. I will comeback when I have an answer...

**Comment by opalrt** [comment] 2023-11-24 03:01
Hi @simonbrowndotje, we confirmed it was nginx and max-payload-size configuration. we change form 1M to 64M.
Everything work well.
We can can close this issue please. (I don't know how :-).
Thanks for your time.
Regards.
Eric PANIER

**Closed** 2023-11-24 11:58 UTC
Labels: can't reproduce
