### ISSUE TITLE
Giving a prompt on the UI when saving fails

### ISSUE THREAD

**Issue by cavies** [structurizr/onpremises#18] opened 2023-02-17 02:09 UTC
I use the version 2956
Sometimes (many times) when I make changes ( in dslEditor or in diagram view) , then save workspace, I will find a problem in the javascript console. The put request returned a 400 status code with the following information
{
    “success”: false,
    “message”: “The workspace could not be saved because a newer version has been created by XXX at XXXX.”
}
![20230217100530](https://user-images.githubusercontent.com/15722487/219531075-0604e8e7-48e6-43fc-8988-3aad02c7acc8.jpg)
![20230217100819](https://user-images.githubusercontent.com/15722487/219531411-344a5183-736f-44cf-b558-db6870841d45.jpg)

However, there is no prompt on the UI, and the “SAVE workspace” button is grayed out. A few times ago, I didn’t know that I didn’t save successfully. After returning to the dashboard, I found that my changes didn’t exist. I felt very disappointed. I wonder if you can consider giving a prompt on the UI when saving fails to avoid this situation.

In addition, I can be sure that no one is editing and uploading this workspace synchronously except me. Why does it fail to save? Why is there a new version? I looked up the open source code on your github and found that this might be caused by the separate storage of workspace metadata and workspace.dsl. I wonder if the metadata update succeeds sometimes, but the workspace.dsl itself fails? (Maybe my guess is wrong, please forgive me)

**Comment by simonbrowndotje** [comment] 2023-02-17 06:40
Are you using the DSL editor and diagram editor simultaneously, in different tabs? If so, that will be the problem - the UI is not designed to be used in that way.

**Comment by cavies** [comment] 2023-02-17 07:57
It can be confirmed that I didn't edit at the same time on different tabs. After I found that there was a problem with dsleditor, I went back to the dashboard and then entered the diagram editor to edit to see if there was still a problem, and then found that there was such a problem wherever I edited. I can only force push a new version through cli before I can edit it again.

**Comment by simonbrowndotje** [comment] 2023-02-17 10:32
I've modified the UI so that it shows the error message in the browser itself. This is available in build 2959+.

The problem you're seeing is when the revision flag in the workspace metadata becomes different from that in the workspace JSON, but I don't understand the cause yet. If it happens again, you can issue the following command in your JavaScript/developer console to reset the revision, which will allow you to save your workspace from the DSL editor/diagram editor page.

```
structurizrApiClient.resetRevision()
```

**Comment by cavies** [comment] 2023-02-17 12:54
I've upgraded to 2959, this version has solved the problem of not knowing the saving failure in time. The next time I encounter a save failure, I will pay attention to what I have done before and check the corresponding log to see if there is any useful information. Thank you for your timely handling.

**Comment by simonbrowndotje** [comment] 2023-03-05 11:38
Marking as resolved - please let me know if the issue happens again.

**Closed by simonbrowndotje** 2023-03-05 11:38 UTC
